server:
  port: 8083

spring:
  application:
    name: network-service 
  cloud:
    consul:
      host: localhost
      port: 8500

      discovery:
        hostname: localhost
        enabled: true
        register: true